config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  resources :projects do
    resources :messages
    resources :labels
    resources :project_permissions
    resources :boards do
      resources :tasks
    end
  end
  resources :tasks do
    resources :task_labels, only: [:create, :new]
    resources :assignees, only: [:create, :new]
    patch 'deadline', to: 'tasks#update_deadline', as: 'deadline'
  end
  # in this code i need three routes that will return a ruby erb file as a text/html so that i can use it in my js file
  get "/add_label_modal", to: "pages#add_label_modal", as: "add_label_modal"
  get "/add_deadline_modal", to: "pages#add_deadline_modal", as: "add_deadline_modal"
  get "/add_assignee_modal", to: "pages#add_assignee_modal", as: "add_assignee_modal"
  get "/message", to: "pages#message", as: "message"
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :project

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :color, presence: true, length: { minimum: 3, maximum: 25 }
  validates :project_id, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :boards, dependent: :destroy
  has_many :project_permissions, dependent: :destroy
  has_many :labels, dependent: :destroy
  has_many :users, through: :project_permissions

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :description, presence: true, length: { minimum: 3, maximum: 250 }
  validates :user_id, presence: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

	def index
    @labels = Label.all
	end

	def show
		@label = Label.find(params[:id])
	end

	def new
		@label = Label.new
		@label.build_address
	end

	def create
		@label = Label.new(label_params)
		@project = Project.find(params[:project_id])
		if @label.save
			redirect_to project_path(@project), notice: 'Label created successfully'
		else
			render json: { status: @label.errors.full_messages }
		end
	end

	def edit
		@label = Label.find(params[:id])
	end

	def update
		@label = Label.find(params[:id])
		@project = Project.find(params[:project_id])
		if @label.update(label_params)
			redirect_to project_path(@project), notice: 'Label updated successfully'
		else
			redirect_to project_path(@project), notice: 'Label cannot be updated'
		end
	end

	def destroy
		@label = Label.find(params[:id])
		# if label is referenced anywhere, it cannot be deleted
		if TaskLabel.where(label_id: @label.id).present?
			redirect_to project_path(@label.project), notice: 'Label cannot be deleted as it is used in a task'
		else
			@label.destroy
			redirect_to project_path(@label.project), notice: 'Label deleted successfully'
		end
	end

	private

	def label_params
		params.require(:label).permit(:name, :color, :project_id)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # do not add if project.user_id = current_user.id
  def index
    all_project_ids = current_user.project_ids + current_user.permitted_project_ids
    @projects = Project.where(id: all_project_ids)
    @project = Project.new
  end

  def show

    @project = Project.find_by_id(params[:id])
    @board = Board.new
    @boards = Board.where(project_id: @project.id)
    @label = Label.new
    @labels = Label.where(project_id: @project.id)
    @task = Task.new
    @tasks = Task.where(project_id: @project.id)
    @project_permission = ProjectPermission.new
    @project_permissions = @project.project_permissions
    @message = Message.new
    @messages = Message.where(project_id: @project.id)
    @assignee = Assignee.new

  end


  def new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created.'
    else
      @projects = Project.all
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

	def update

		if @project.update(project_params)
			redirect_to project_path(@project), notice: 'Project was successfully updated.'
		else
			render :index, status: :unprocessable_entity
		end
	end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    if Project.find_by_id(params[:id])
      @project = Project.find_by_id(params[:id])
    else
      @project = Project.find_by_id(params[:project_id])
    end
  end

  def project_params
    params.require(:project).permit(:name, :description, :user_id)
  end
end

app/views/shared/projects/labels/_add.html.erb
<div class="modal fade" id="addLabelModal-<%= task.id %>" tabindex="-1" aria-labelledby="addLabelModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-opened-content">
      <%= render "shared/modals/header" do %>
        <h5 class="modal-title" id="addLabelModalLabel">Add labels to the task <%= task.name %></h5>
        <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "modal" } %>
      <% end %>
      <%= render "shared/modals/content" do %>
        <%= form_tag task_task_labels_path(task), method: :post, remote: true, class: "form p-2" do %>
          <% @project.labels.each do |label| %>
            <% bgcolor = label.color %>
            <div class="p-2 my-2 rounded-2" style="background-color: <%= bgcolor %>;">
              <input type="checkbox" name="label_ids[]" id="label_ids_<%= label.id %>" value="<%= label.id %>" class="form-check-input label-checkbox" <%= "checked" if task.task_labels.find_by(label_id: label.id) %>>
              <%= label_tag "label_ids_#{label.id}", label.name, class: "form-check-label" %>
            </div>
          <% end %>
          <%= hidden_field_tag "task_id", task.id %>
          <%= render "shared/modals/footer" do %>
            <%= submit_tag "Update Labels", class: "main-btn", data: { bs_dismiss: "modal" } %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/projects/labels/_create.html.erb
<div class="modal fade" id="createLabelModal" tabindex="-1" aria-labelledby="createLabelModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-opened-content">
      <%= render "shared/modals/header" do %>
        <h5 class="modal-title" id="createLabelModalLabel">Create Label</h5>
        <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "modal" } %>
      <% end %>
      <%= render "shared/modals/content" do %>
        <%= form_for @label, url: project_labels_path(@project), method: :post, remote: true, html: { class: "form" } do |f| %>
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-input", placeholder: "Name Label", autocomplete: "off" %>
          <% if @project.errors.full_messages_for(:name).any? %>
            <p class="text-danger"><%= @project.errors.full_messages_for(:name).first %></p>
          <% end %>
          <%= f.label :color, class: "form-label mt-3" %>
            <%= f.color_field :color, id: "Color_field_button", class: "form-input", placeholder: "Color Label", value: @label.color %>

          <% if @project.errors.full_messages_for(:color).any? %>
            <p class="text-danger"><%= @project.errors.full_messages_for(:color).first %></p>
          <% end %>
          <% if @project.errors.full_messages_for(:color).any? %>
            <p class="text-danger"><%= @project.errors.full_messages_for(:color).first %></p>
          <% end %>
          <%= f.hidden_field :project_id, value: @project.id %>
          <%= render "shared/modals/footer" do %>
            <%= f.button :submit, class: "main-btn" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/projects/labels/_labels.html.erb
<div class="modal fade" id="showLabelModal" tabindex="-1" aria-labelledby="showLabelModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-opened-content">
      <%= render "shared/modals/header" do %>
        <h5 class="modal-title" id="showLabelModalLabel">Edit Labels</h5>
        <div>
          <button type="button" class="main-btn" data-bs-toggle="modal" data-bs-target="#createLabelModal">
            New Label
          </button>
          <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "modal" } %>
        </div>
      <% end %>
      <%= render "shared/modals/content" do %>
        <% if @project.labels.any? %>
          <% @project.labels.each do |label| %>
            <%= form_for label, url: project_label_path(@project, label), method: :patch, remote: true, html: { class: "form" } do |f| %>
              <%= f.label :name, class: "mt-4 form-label" %>
              <%= f.text_field :name, class: "form-input", placeholder: "Name Label", value: label.name, autocomplete: "off" %>
              <% if label.errors.full_messages_for(:name).any? %>
                <p class="text-danger"><%= label.errors.full_messages_for(:name).first %></p>
              <% end %>
              <%= f.label :color, class: "form-label mt-3" %>
              <%= f.color_field :color, id: "Color_field_button", class: "form-input w-100", placeholder: "Color Label", value: label.color %>
              <% if label.errors.full_messages_for(:color).any? %>
                <p class="text-danger"><%= label.errors.full_messages_for(:color).first %></p>
              <% end %>
              <%= f.hidden_field :project_id, value: @project.id %>
              <%= render "shared/modals/footer" do %>
                <%= f.button "Update Label", class: "main-btn" %>
              <% end %>
            <% end %>
            <%= form_for label, url: project_label_path(@project, label), method: :delete, remote: true, html: { class: "form" } do |f| %>
                <%= f.button "Delete Label", class: "main-btn minus-margin modal-footer" %>
            <% end %>
          <% end %>
        <% else %>
          <p>No labels found.</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/projects/labels/create' %>