config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  resources :projects do
    resources :messages
    resources :labels
    resources :project_permissions
    resources :boards do
      resources :tasks
    end
  end
  resources :tasks do
    resources :task_labels, only: [:create, :new]
    resources :assignees, only: [:create, :new]
    patch 'deadline', to: 'tasks#update_deadline', as: 'deadline'
  end
  # in this code i need three routes that will return a ruby erb file as a text/html so that i can use it in my js file
  get "/add_label_modal", to: "pages#add_label_modal", as: "add_label_modal"
  get "/add_deadline_modal", to: "pages#add_deadline_modal", as: "add_deadline_modal"
  get "/add_assignee_modal", to: "pages#add_assignee_modal", as: "add_assignee_modal"
  get "/message", to: "pages#message", as: "message"
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :project

  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :description, presence: true, length: { minimum: 3, maximum: 250 }
  validates :project_id, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :boards, dependent: :destroy
  has_many :project_permissions, dependent: :destroy
  has_many :labels, dependent: :destroy
  has_many :users, through: :project_permissions

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :description, presence: true, length: { minimum: 3, maximum: 250 }
  validates :user_id, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_project, only: [:create, :show]
	def index
		@boards = Board.where(project_id: params[:id])
    @board = Board.new
	end

	def show
		@board = Board.find_by(id: params[:id])
	end

	def new
		@board = Board.new
	end

	def create
		@board = Board.new
		@labels = Label.where(project_id: params[:project_id])
		@label = Label.new
		@board.name = params[:board][:name]
    @board.description = params[:board][:description]
    @board.project_id = params[:project_id]

		if @board.save
			redirect_to project_path(@project), notice: 'Board was successfully created.'
		else
			@boards = Board.where(project_id: params[:project_id])
			render "projects/show", status: :unprocessable_entity
		end
	end

	def edit
		@board = Board.find_by(id: params[:id])
	end

	def update
    
		@board = Board.find_by(id: params[:id])

		@board.name = params[:board][:name]
		@board.save
	end

	def destroy
		@board = Board.find_by(id: params[:id])
		@board.destroy
		redirect_to projects_path
	end
  def set_project
    @project = Project.find_by_id(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # do not add if project.user_id = current_user.id
  def index
    all_project_ids = current_user.project_ids + current_user.permitted_project_ids
    @projects = Project.where(id: all_project_ids)
    @project = Project.new
  end

  def show

    @project = Project.find_by_id(params[:id])
    @board = Board.new
    @boards = Board.where(project_id: @project.id)
    @label = Label.new
    @labels = Label.where(project_id: @project.id)
    @task = Task.new
    @tasks = Task.where(project_id: @project.id)
    @project_permission = ProjectPermission.new
    @project_permissions = @project.project_permissions
    @message = Message.new
    @messages = Message.where(project_id: @project.id)
    @assignee = Assignee.new

  end


  def new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created.'
    else
      @projects = Project.all
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

	def update

		if @project.update(project_params)
			redirect_to project_path(@project), notice: 'Project was successfully updated.'
		else
			render :index, status: :unprocessable_entity
		end
	end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    if Project.find_by_id(params[:id])
      @project = Project.find_by_id(params[:id])
    else
      @project = Project.find_by_id(params[:project_id])
    end
  end

  def project_params
    params.require(:project).permit(:name, :description, :user_id)
  end
end

app/views/shared/projects/boards/_assignee.html.erb
<div class="modal fade" id="showAssigneeModal-<%= task.id %>" tabindex="-1" aria-labelledby="showAssigneeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-opened-content">
      <%= render "shared/modals/header" do %>
        <h5 class="modal-title" id="showAssigneeModalLabel">Add assignees to the task <%= task.name %></h5>
        <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "modal" } %>
      <% end %>
      <%= render "shared/modals/content" do %>
        <%= form_tag task_assignees_path(task), method: :post, remote: true, class: "form p-2" do %>
          <% users = @project.users + [@project.user] %>
          <% users.each do |user| %>
            <div class="d-flex justify-content-between align-items-center my-2">
              <div class="p-2 my-2 rounded-2">
                <input type="checkbox" name="user_ids[]" id="user_ids_<%= user.id %>" value="<%= user.id %>" class="form-check-input label-checkbox" <%= "checked" if task.assignees.find_by(user_id: user.id) %>>
                <%= label_tag "user_ids_#{user.id}", "#{user.first_name} #{user.last_name} (#{user.email})", class: "form-check-label" %>
              </div>
            </div>
          <% end %>
          <%= hidden_field_tag "task_id", task.id %>
          <%= render "shared/modals/footer" do %>
            <%= submit_tag "Update Assignees", class: "main-btn", data: { bs_dismiss: "modal" } %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/projects/boards/_card.html.erb
<div class="drag-container"></div>
<div class="board mx-3" data-controller="muuri">

  <% boards.each do |board| %>
    <div class="board-column py-3">
      <div class="board-column-container" data-controller="edit-board">
        <div class="board-column-header p-0"  >
          <div data-edit-board-target="card">
            <div data-edit-board-target="infos" class="px-4">
              <span data-action="click->edit-board#displayForm">
                <span class="to-disable-btn" data-controller="popovers" data-bs-toggle="popover" data-bs-trigger="hover" data-bs-placement="right" data-bs-content="<%= board.description %>">
                  <%= board.name %>
                </span>
              </span>
            </div>
            <%= render "shared/projects/boards/form", project: @project, board: board %>
          </div>
        </div>
        <div class="board-column-content-wrapper">
          <div class="board-column-content" id="board-<%= board.id %>" >
            <% board.tasks.each do |task| %>
              <%= render "shared/projects/boards/task", task: task %>
            <% end %>
          </div>
        </div>
        <div class="board-column-footer">
          <div class="bg-background px-3 rounded-2 py-2 w-100 add-task-btn" id="add-task-<%= board.id %>" data-muuri-target="infos-<%= board.id %>" data-action="click->muuri#showForm" data-board-id="<%= board.id %>">
            Add Task
          </div>
          <%= render "shared/projects/tasks/create", project: @project, board: board, task: @task %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% boards.each do |board| %>
  <% board.tasks.each do |task| %>
    <%= render "shared/projects/labels/add", task: task %>
    <%= render "shared/projects/boards/deadline", task: task, board: board %>
    <%= render "shared/projects/boards/assignee", task: task, board: board %>
  <% end %>
<% end %>

<%= render 'shared/projects/chat/chat_offcanvas' %>

app/views/shared/projects/boards/_create.html.erb
<div class="modal fade" id="createBoardModal" tabindex="-1" aria-labelledby="createBoardModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-opened-content">
      <%= render "shared/modals/header" do %>
        <h5 class="modal-title" id="createProjectBoardLabel">Create Board</h5>
        <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "modal" } %>
      <% end %>
      <%= render "shared/modals/content" do %>
        <%= form_for [project, board] do |f| %>
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-input", placeholder: "Board Name", autocomplete: "off" %>
          <% if board.errors.full_messages_for(:name).any? %>
            <p class="text-danger"><%= board.errors.full_messages_for(:name).first %></p>
          <% end %>
          <%= f.label :description, class: "form-label mt-3" %>
          <%= f.text_area :description, class: "form-input", placeholder: "Board Description", autocomplete: "off" %>
          <% if board.errors.full_messages_for(:description).any? %>
            <p class="text-danger"><%= board.errors.full_messages_for(:description).first %></p>
          <% end %>
          <%= render "shared/modals/footer" do %>
            <%= f.button :submit, class: "main-btn" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/projects/boards/_deadline.html.erb
<div class="modal fade" id="addDeadLineModal-<%= task.id %>" tabindex="-1" aria-labelledby="addDeadLineModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-opened-content">
      <%= render "shared/modals/header" do %>
        <h5 class="modal-title" id="addDeadLineModalLabel">Set deadline to the task</h5>
        <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "modal" } %>
      <% end %>
      <%= render "shared/modals/content" do %>
        <%= form_for task, url: task_deadline_path(task), method: :patch, remote: true, html: { class: "form" } do |f| %>
          <%= f.datetime_field :deadline, class: "form-input" %>

          <%= hidden_field_tag "task_id", task.id %>
          <%= render "shared/modals/footer" do %>
            <%= submit_tag "Update DeadLine", class: "main-btn" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/projects/boards/_form.html.erb
<%= form_for [project, board],
  html: {
    class: "d-none",
    data: {
      edit_board_target: "form",
      action: "keyup->edit-board#update"
    }
  } do |f|
%>
  <%= f.text_field :name, class: " bg-dark-background rounded-2 align-items-center text-light-grey w-100 px-4 border-color-purple m-0"%>
<% end %>

app/views/shared/projects/boards/_task.html.erb
<div class="board-item" id="board-<%= task.board.id %>-task-<%= task.id %>">
    <div class="task-container bg-background py-2 px-3 rounded-2 mt-2 hover-pointer d-flex flex-column justify-content-between w-100">
        <div class="text-light-grey fw-light <%= 'text-red fw-normal' if task.deadline && task.deadline <= Time.now %> fs-6 d-flex align-items-center">
            <%= task.deadline.strftime("%d %b %Y") if task.deadline %>
            <div class="d-flex">
                <% task.assignees.each do |assignee| %>
                    <div class="rounded-circle bg-dark-purple p-1 text-center text-light-grey mb-2 assignee <%= 'ms-2' if task.deadline %><%= 'me-2' if !task.deadline %>">
                        <%= assignee.user.first_name.split("").first + assignee.user.last_name.split("").first %>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="d-flex flex-wrap">
            <% task.task_labels.each do |task_label| %>
                <div class="text-light-grey label rounded-2 px-1 py-1 fs-6 me-2 mb-2" style="background-color: <%= task_label.label.color %>">
                    <%= task_label.label.name %>
                </div>
            <% end %>
        </div>
        <div>
            <div class="text-light-grey fs-6 mb-0 overflow-hidden" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                <%= task.name %>
            </div>
            <div class="icons bg-background p-2 h-100 d-flex align-items-center pe-0">
                <%= image_tag "https://svgshare.com/i/xKJ.svg", class: "to-disable-btn icon-task", data: { bs_toggle: "modal", bs_target: "#addDeadLineModal-#{task.id}" }, id: "addDeadLineModalButton"%>
                <% if task.board.project.labels.any? %>
                    <%= image_tag "https://svgshare.com/i/xKV.svg", class: "to-disable-btn icon-task", data: { bs_toggle: "modal", bs_target: "#addLabelModal-#{task.id}" }, id: "addLabelModalButton"%>
                <% end %>
                <%= image_tag "https://svgshare.com/i/xJ2.svg", class: "to-disable-btn icon-task", data: { bs_toggle: "modal", bs_target: "#showAssigneeModal-#{task.id}" }, id: "showAssigneeModalButton"%>
    

            </div>
        </div>
    </div>
</div>