config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  resources :projects do
    resources :messages
    resources :labels
    resources :project_permissions
    resources :boards do
      resources :tasks
    end
  end
  resources :tasks do
    resources :task_labels, only: [:create, :new]
    resources :assignees, only: [:create, :new]
    patch 'deadline', to: 'tasks#update_deadline', as: 'deadline'
  end
  # in this code i need three routes that will return a ruby erb file as a text/html so that i can use it in my js file
  get "/add_label_modal", to: "pages#add_label_modal", as: "add_label_modal"
  get "/add_deadline_modal", to: "pages#add_deadline_modal", as: "add_deadline_modal"
  get "/add_assignee_modal", to: "pages#add_assignee_modal", as: "add_assignee_modal"
  get "/message", to: "pages#message", as: "message"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible py-2 px-3 fade show m-1 d-flex justify-content-between align-items-center" role="alert">
    <%= notice %>
    <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon rotate-45", data: { bs_dismiss: "alert" } %>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="bg-dark-background">
  <div class="container py-3">
    <div class="d-flex gap-5 align-items-center justify-content-between">
      <%= link_to projects_path do %>
        <%= image_tag "logo.png", class: "logo" %>
      <% end %>
      <div class="mx-4 text-light-grey fs-4"><%= @project.name %></div>
      <div>
        <%= image_tag "https://svgshare.com/i/xKV.svg", class: "icon", data: { bs_toggle: "modal", bs_target: "#showLabelModal" }, id: "showLabelModalButton" %>
        <%= image_tag "https://svgshare.com/i/xJ1.svg", class: "icon", data: { bs_toggle: "modal", bs_target: "#createBoardModal" }, id: "createBoardModalButton" %>
        <%= image_tag "https://svgshare.com/i/xLf.svg", class: "icon", data: { bs_toggle: "offcanvas", bs_target: "#chatOffCanvas" }, id: "chatOffCanvasButton" %>
        <%= image_tag "https://svgshare.com/i/xKw.svg", class: "icon", data: { bs_toggle: "modal", bs_target: "#editMembersModal" }, id: "editMembersModalButton" %>
        <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "mx-2 main-btn fs-6" %>
        <%= image_tag "https://svgshare.com/i/xJn.svg", class: "icon", data: { bs_toggle: "modal", bs_target: "#editProjectModal" }, id: "editProjectModalButton" %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/projects/edit' %>
<%= render 'shared/projects/labels/labels' %>
<%= render 'shared/projects/members/edit' %>